name: Recepies
settings:
  CODE_SIGNING_ALLOWED: NO
  ASSETCATALOG_COMPILER_GENERATE_ASSET_SYMBOLS: true
  ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: true

options:
 bundleIdPrefix: com.zmey666
 deploymentTarget:
  iOS: "15.0"
  postGenCommand: pod install
packages:
  SortingButtonPackage:
    url: https://github.com/DmitryLorents/SortingButtonPackage
    majorVersion: 1.0.0
targets:
  Recepies:
    

    type: application
    platform: iOS
    sources:
      - Recepies
    dependencies:
      - package: SortingButtonPackage

    attributes: 
    postCompileScripts:
      - script: |
          if [[ "$(uname -m)" == arm64 ]]; then export PATH="/opt/homebrew/bin:$PATH"
          fi

          if which swiftformat >/dev/null; then swiftformat .
          else
          echo "warning: SwiftFormat not installed, download from https://github.com/nicklockwood/SwiftFormat"
          fi
        name: Swiftformat

      - script: |
          #if [[ "$(uname -m)" == arm64 ]]; then export PATH="/opt/homebrew/bin:$PATH"
          #fi

          #if which swiftlint > /dev/null; then swiftlint
          #else
          #echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          #fi

        name: Swiftlint

      - script: |
          if [[ "$(uname -m)" == arm64 ]]; then export PATH="/opt/homebrew/bin:$PATH"
          fi

          if which swiftgen >/dev/null; then swiftgen
          else
          echo "warning: Swiftgen not installed, download from"
          fi

        name: Swifgen