name: Recepies
settings:
  CODE_SIGNING_ALLOWED: NO
options:
 bundleIdPrefix: com.zmey666
 deploymentTarget:
  iOS: "15.0"
  postGenCommand: pod install
packages:
  SortingButtonPackage:
    url: https://github.com/DmitryLorents/SortingButtonPackage
    majorVersion: 1.0.0
targets:
  Recepies:
    attributes:
      
    postCompileScripts:
      - script: |
          if [[ "$(uname -m)" == arm64 ]]; then export PATH="/opt/homebrew/bin:$PATH"
          fi

          if which swiftformat >/dev/null; then swiftformat .
          else
          echo "warning: SwiftFormat not installed, download from https://github.com/nicklockwood/SwiftFormat"
          fi
        name: Swiftformat

      - script: |
          if [[ "$(uname -m)" == arm64 ]]; then export PATH="/opt/homebrew/bin:$PATH"
          fi

          if which swiftlint > /dev/null; then swiftlint
          else
          echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi

        name: Swiftlint

      - script: |
          if [[ "$(uname -m)" == arm64 ]]; then export PATH="/opt/homebrew/bin:$PATH"
          fi

          if which swiftgen >/dev/null; then swiftgen
          else
          echo "warning: Swiftgen not installed, download from"
          fi

        name: Swifgen
      
    type: application
    platform: iOS

    sources:
      - Recepies
    dependencies:
      - package: SortingButtonPackage